chore: Yt validate with state
KemuriTechnology/front_theyyam pull request #58
Opened 2023-07-12 09:13 UTC by dipeshkemuri

2023-07-18 08:51 UTC, akshay-kh requested changes

2023-07-18 08:51 UTC, akshay-kh commented on src/components/UpcomingEvents.vue
> +              event.target?.firstElementChild?.setAttribute('src', 'https://www.youtube.com/embed/' + validUID + '?autoplay=1&mute=1&controls=0');
use template literal

2023-07-18 08:51 UTC, akshay-kh commented on src/components/EventsTemplate.vue
> +          event.target?.firstElementChild?.setAttribute('src', 'https://www.youtube.com/embed/' + validUID + '?autoplay=1&mute=1&controls=0');
use template literal

2023-07-18 08:51 UTC, akshay-kh commented on src/components/UpcomingEvents.vue
> +
maybe this change is not required ?

2023-07-19 08:11 UTC, dipeshkemuri commented on src/components/EventsTemplate.vue
> +          event.target?.firstElementChild?.setAttribute('src', 'https://www.youtube.com/embed/' + validUID + '?autoplay=1&mute=1&controls=0');
Applied

2023-07-19 08:11 UTC, dipeshkemuri commented on src/components/UpcomingEvents.vue
> +              event.target?.firstElementChild?.setAttribute('src', 'https://www.youtube.com/embed/' + validUID + '?autoplay=1&mute=1&controls=0');
Applied

2023-07-20 05:48 UTC, akshay-kh approved these changes

2023-07-20 10:48 UTC, merged