chore: Edit page for editing event
KemuriTechnology/front_theyyam pull request #67
Opened 2023-07-28 12:46 UTC by dipeshkemuri

2023-07-28 13:00 UTC, akshay-kh requested changes
@dipeshkemuri please check

2023-07-28 13:01 UTC, akshay-kh commented
@dipeshkemuri please check why deploy failed for this change

2023-07-28 13:09 UTC, dipeshkemuri commented on src/pages/event/[id]/edit.vue
> +    ext_36: eventData.details.contacts[3].phones[2],
@akshay-kh san because we have different properties name in response and while updating we have different name

2023-07-28 13:11 UTC, dipeshkemuri commented on src/pages/event/[id]/edit.vue
> +  const bodyStructure = {
@akshay-kh san changed

2023-07-28 13:13 UTC, dipeshkemuri commented on src/pages/event/[id]/edit.vue
> +    }
@akshay-kh san overwriting thing sorted but loop part cant be as properties name different

2023-08-01 05:49 UTC, akshay-kh approved these changes

2023-08-01 13:31 UTC, merged