chore: seo updates
KemuriTechnology/front_theyyam pull request #92
Opened 2023-08-18 11:47 UTC by dipeshkemuri

2023-08-18 12:03 UTC, akshay-kh requested changes

2023-08-18 12:03 UTC, akshay-kh commented on src/public/sitemap.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@dipeshkemuri can you try this to generate sitemap dynamically

2023-08-21 12:10 UTC, dipeshkemuri commented on src/public/sitemap.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@akshay-kh san FB applied

2023-08-24 06:57 UTC, akshay-kh approved these changes

2023-08-24 07:01 UTC, merged